### ISSUE TITLE
Install_clif script bails out generating proto_util.cc

### ISSUE THREAD

**Issue by davidavdav** [pykaldi/pykaldi#120] opened 2019-04-30 12:22 UTC
Hello, 

I have a kaldi patch for #113, but in order to test this I need to install the whole of pykaldi.  On my mac I run into trouble, when I try to follow the instructions in the readme.  

I am not sure whether this is a problem of the script `tools/install_clif.sh` or of clif, or of my own environment, but I get a strange error running the script:
```
...
[2/5] Generating proto_util.cc, proto_util.h, proto_util.init.cc
FAILED: tools/clif/python/utils/proto_util.cc tools/clif/python/utils/proto_util.h tools/clif/python/utils/proto_util.init.cc 
cd /Users/david/src/pykaldi/tools/clif_backend/build_matcher/tools/clif/python/utils && PYTHONPATH=/Users/david/src/pykaldi/tools/clif_backend/build_matcher/tools:/Users/david/src/pykaldi/tools/clif_backend/llvm/tools /Users/david/src/pykaldi/env/bin/python /Users/david/src/pykaldi/tools/clif_backend/llvm/tools/clif/pyclif.py -p/Users/david/src/pykaldi/tools/clif_backend/llvm/tools/clif/python/types.h -c/Users/david/src/pykaldi/tools/clif_backend/build_matcher/tools/clif/python/utils/proto_util.cc -g/Users/david/src/pykaldi/tools/clif_backend/build_matcher/tools/clif/python/utils/proto_util.h -i/Users/david/src/pykaldi/tools/clif_backend/build_matcher/tools/clif/python/utils/proto_util.init.cc -I/Users/david/src/pykaldi/tools/clif_backend/llvm/tools -I/Users/david/src/pykaldi/tools/clif_backend/build_matcher/tools --modname=clif.python.utils.proto_util --matcher_bin=/Users/david/src/pykaldi/tools/clif_backend/build_matcher/bin/clif-matcher "-f-I/Users/david/src/pykaldi/env/include/python3.7m -I/Users/david/src/pykaldi/tools/clif_backend/llvm/tools -I/Users/david/src/pykaldi/tools/clif_backend/build_matcher/tools -I/Users/david/src/pykaldi/tools/protobuf/include -isystem /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -std=c++11 " /Users/david/src/pykaldi/tools/clif_backend/llvm/tools/clif/python/utils/proto_util.clif
Traceback (most recent call last):
  File "/Users/david/src/pykaldi/tools/clif_backend/llvm/tools/clif/pyclif.py", line 38, in <module>
    from clif.python import gen, pyext, pytd2proto  # pylint: disable=g-multiple-import
  File "/Users/david/src/pykaldi/tools/clif_backend/llvm/tools/clif/python/gen.py", line 737
    def IterNext(wrapped_iter, async, postconversion):
                                   ^
SyntaxError: invalid syntax
ninja: build stopped: subcommand failed.
```
I can't see why that `.py` source is invalid there---it is a kind of python that I am not familiar with, but things look not much different around line 737 from the other lines of the source.

**Comment by vrmpx** [comment] 2019-04-30 20:49
I think the issue is that `async` is a keyword in python 3.7.

**Comment by vrmpx** [comment] 2019-04-30 23:33
So I just merged a PR into our fork of clif that addresses this issue. Please pull the changes and re-install clif (from scratch preferably).

**Comment by davidavdav** [comment] 2019-05-01 07:14
Thanks, I last night I had also come to the conclusion that it must have been a async/python3.7 keyword.  Which apparently means that CLIF can't deal with python 3.7.  Thanks I will try again.

**Comment by davidavdav** [comment] 2019-05-01 08:24
The `async` bug seems to have gone, but I am now hitting another esoteric bug: "stdio.h" is not found!  How can stdio.h, of all files, with such a multitude of toolchains helping us to compile, not be found so late in the process?  
```
...
[1785/1788] Generating proto_util.cc, proto_util.h, proto_util.init.cc
FAILED: tools/clif/python/utils/proto_util.cc tools/clif/python/utils/proto_util.h tools/clif/python/utils/proto_util.init.cc 
cd /Users/david/src/pykaldi/tools/clif_backend/build_matcher/tools/clif/python/utils && PYTHONPATH=/Users/david/src/pykaldi/tools/clif_backend/build_matcher/tools:/Users/david/src/pykaldi/tools/clif_backend/llvm/tools /Users/david/src/pykaldi/env/bin/python /Users/david/src/pykaldi/tools/clif_backend/llvm/tools/clif/pyclif.py -p/Users/david/src/pykaldi/tools/clif_backend/llvm/tools/clif/python/types.h -c/Users/david/src/pykaldi/tools/clif_backend/build_matcher/tools/clif/python/utils/proto_util.cc -g/Users/david/src/pykaldi/tools/clif_backend/build_matcher/tools/clif/python/utils/proto_util.h -i/Users/david/src/pykaldi/tools/clif_backend/build_matcher/tools/clif/python/utils/proto_util.init.cc -I/Users/david/src/pykaldi/tools/clif_backend/llvm/tools -I/Users/david/src/pykaldi/tools/clif_backend/build_matcher/tools --modname=clif.python.utils.proto_util --matcher_bin=/Users/david/src/pykaldi/tools/clif_backend/build_matcher/bin/clif-matcher "-f-I/Users/david/src/pykaldi/env/include/python3.7m -I/Users/david/src/pykaldi/tools/clif_backend/llvm/tools -I/Users/david/src/pykaldi/tools/clif_backend/build_matcher/tools -I/Users/david/src/pykaldi/tools/protobuf/include -isystem /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -std=c++11 " /Users/david/src/pykaldi/tools/clif_backend/llvm/tools/clif/python/utils/proto_util.clif
In file included from /dev/stdin:1:
In file included from /Users/david/src/pykaldi/tools/clif_backend/llvm/tools/clif/python/types.h:27:
In file included from /Users/david/src/pykaldi/env/include/python3.7m/Python.h:25:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/stdio.h:108:15: fatal error: 'stdio.h' file not found
#include_next <stdio.h>
              ^~~~~~~~~
_BackendError: Matcher failed with status 1
```
I am consistently hitting this error, I've completely removed pykaldi and reinstalled everything from scratch according to the README, but to no avail.  It is probably some weird configuration on my (mac) side, but then again, it looks like some basic include directory is missing.

**Comment by davidavdav** [comment] 2019-05-03 10:01
I just can't seem to let this go, as this frustrates me big time...  So the build command can be fixed by inserting a 
```
-isystem /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/
```
just before the `-std=c++11`, but I have no clue where to set this.  The command is used by ninja, that appears to use CMake, that is supposed to use a file CMakeList.txt, of which there are millions around.  

In `install_clif.sh` there is `CXX_SYSTEM_INCLUDE_DIR_FLAGS="-DCXX_SYSTEM_INCLUDE_DIR=$CXX_SYSTEM_INCLUDE_DIR"` but the very name suggests there is room for only a single system include dir...

**Comment by davidavdav** [comment] 2019-05-07 09:19
OK, I can get CLIF to compile by manually patching the `tools/clif/build.ninja
```
cat build.ninja | sed 's|-isystem /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1|-isystem /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -isystem /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/|' > build.ninja.patched
mv build.ninja.patched build.ninja
```
and put this right before `"$MAKE_OR_NINJA" "${MAKE_PARALLELISM[@]}" clif-matcher clif_python_utils_proto_util` in `install_clif.sh`

Then I need to patch `setup.py` using
```
diff --git a/setup.py b/setup.py
index 5a0ce13..194a4bc 100644
--- a/setup.py
+++ b/setup.py
@@ -127,7 +127,7 @@ if platform.system() == "Darwin":
               "line tools, e.g. xcode-select --install", file=sys.stderr)
         sys.exit(1)
     CXX_SYSTEM_INCLUDE_DIR = os.path.join(TOOLCHAIN_DIR, "usr/include/c++/v1")
-    CLIF_CXX_FLAGS += " -isystem {}".format(CXX_SYSTEM_INCLUDE_DIR)
+    CLIF_CXX_FLAGS += " -isystem {} -isystem {}".format(CXX_SYSTEM_INCLUDE_DIR, "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/")
     LD_FLAGS += " -undefined dynamic_lookup"
 elif platform.system() == "Linux":
     CXX_FLAGS += " -Wno-maybe-uninitialized"
```

This all obviously is a kludge, I am sure this can be done more neatly somewhere in the setup files, but it helps me out for now.  I won't touch a thing....

**Closed** 2019-12-06 17:22 UTC

**Comment by kkawabat** [comment] 2020-03-24 05:35
Thanks @davidavdav I was having a similar issue where `clif_python_utils_proto_util` was failing because of search path issue that could be fixed with an extra isysroot to the macos.sdk.

```
FAILED: tools/clif/python/utils/proto_util.cc tools/clif/python/utils/proto_util.h tools/clif/python/utils/proto_util.init.cc 
cd /Users/kankawabata/Documents/auralanalytics/analytics_engine/pykaldi/tools/clif_backend/build_matcher/tools/clif/python/utils && PYTHONPATH=/Users/kankawabata/Documents/auralanalytics/analytics_engine/pykaldi/tools/clif_backend/build_matcher/tools:/Users/kankawabata/Documents/auralanalytics/analytics_engine/pykaldi/tools/clif_backend/llvm/tools /Users/kankawabata/Documents/auralanalytics/analytics_engine/venv/bin/python /Users/kankawabata/Documents/auralanalytics/analytics_engine/pykaldi/tools/clif_backend/llvm/tools/clif/pyclif.py -p/Users/kankawabata/Documents/auralanalytics/analytics_engine/pykaldi/tools/clif_backend/llvm/tools/clif/python/types.h -c/Users/kankawabata/Documents/auralanalytics/analytics_engine/pykaldi/tools/clif_backend/build_matcher/tools/clif/python/utils/proto_util.cc -g/Users/kankawabata/Documents/auralanalytics/analytics_engine/pykaldi/tools/clif_backend/build_matcher/tools/clif/python/utils/proto_util.h -i/Users/kankawabata/Documents/auralanalytics/analytics_engine/pykaldi/tools/clif_backend/build_matcher/tools/clif/python/utils/proto_util.init.cc -I/Users/kankawabata/Documents/auralanalytics/analytics_engine/pykaldi/tools/clif_backend/llvm/tools -I/Users/kankawabata/Documents/auralanalytics/analytics_engine/pykaldi/tools/clif_backend/build_matcher/tools --modname=clif.python.utils.proto_util --matcher_bin=/Users/kankawabata/Documents/auralanalytics/analytics_engine/pykaldi/tools/clif_backend/build_matcher/bin/clif-matcher "-f-I/Users/kankawabata/.pyenv/versions/3.7.4/include/python3.7m -I/Users/kankawabata/Documents/auralanalytics/analytics_engine/pykaldi/tools/clif_backend/llvm/tools -I/Users/kankawabata/Documents/auralanalytics/analytics_engine/pykaldi/tools/clif_backend/build_matcher/tools -I/Users/kankawabata/Documents/auralanalytics/analytics_engine/pykaldi/tools/protobuf/include -isystem /Library/Developer/CommandLineTools/usr/include/c++/v1 -std=c++11 " /Users/kankawabata/Documents/auralanalytics/analytics_engine/pykaldi/tools/clif_backend/llvm/tools/clif/python/utils/proto_util.clif
In file included from /dev/stdin:1:
In file included from /Users/kankawabata/Documents/auralanalytics/analytics_engine/pykaldi/tools/clif_backend/llvm/tools/clif/python/types.h:27:
In file included from /Users/kankawabata/.pyenv/versions/3.7.4/include/python3.7m/Python.h:63:
In file included from /Users/kankawabata/.pyenv/versions/3.7.4/include/python3.7m/pyport.h:191:
/Library/Developer/CommandLineTools/usr/include/c++/v1/math.h:301:15: fatal error: 'math.h' file not found
#include_next <math.h>
              ^~~~~~~~
_BackendError: Matcher failed with status 1
```

your suggestion gave me a lead on how to fix it

**Comment by kkawabat** [comment] 2020-07-18 21:13
@davidavdav, you probably don't need this anymore but I found an easier way to set the system paths in the  `install_clif.sh` by setting `cxx_system_include_dir` with:

    CXX_SYSTEM_INCLUDE_DIR="/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -isystem /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/"

essentially CXX_SYSTEM_INCLUDE_DIR sets cxx flags in [CLIFUtils.cmake](https://github.com/pykaldi/clif/blob/a8de9c65cd34a86dbb05ed01eaac39fcb7eb3e68/clif/cmake/modules/CLIFUtils.cmake#L181) with:

```CMake
if (CXX_SYSTEM_INCLUDE_DIR)
    set(ISYSTEM_CXX_FLAGS "-isystem ${CXX_SYSTEM_INCLUDE_DIR}")
  endif(CXX_SYSTEM_INCLUDE_DIR)
```

So you can just additional additional system dir 

     CXX_SYSTEM_INCLUDE_DIR="path1 -isystem path2 ... -isystem path3"
