### ISSUE TITLE
[Question] How to get the numpy from compute_kaldi_pitch?

### ISSUE THREAD

**Issue by kamo-naoyuki** [pykaldi/pykaldi#71] opened 2018-12-25 07:40 UTC
I'm a new of pykalid. 

I understand that `Matrix` class has `numpy` method, but got following error.

```python
import numpy
from kaldi.matrix import Vector
from kaldi.feat.pitch import compute_and_process_kaldi_pitch
from kaldi.feat.pitch import ProcessPitchOptions
from kaldi.feat.pitch import PitchExtractionOptions

wave = Vector(numpy.random.randint(-128, 128, 1000))
x = compute_and_process_kaldi_pitch(PitchExtractionOptions(), ProcessPitchOptions(), wave)
print(x.numpy())
```

```
AttributeError: '_kaldi_matrix.Matrix' object has no attribute 'numpy'
```

**Comment by dogancan** [comment] 2018-12-25 09:20
Thanks for the nice report! This happened because we forgot to convert the output of pitch extraction functions to `Matrix` objects defined in `kaldi.matrix` module. I just pushed a fix for this.

If you had installed pykaldi from source, you are in luck. All you need to do is the following and your code should start working as intended.

```
cd pykaldi
git pull
python setup.py install
```

If you had installed pykaldi via conda, then you will have to wait for the conda package to be updated. We regularly update our conda package but it might take longer than usual due to holidays. In the meantime you can work around this bug by explicitly converting the output of the function to a `Matrix` object, e.g.

```
from kaldi.matrix import Matrix
...
x = Matrix(compute_and_process_kaldi_pitch(PitchExtractionOptions(), ProcessPitchOptions(), wave))
```

**Closed by dogancan** 2018-12-25 09:20 UTC
