### ISSUE TITLE
Request support online2-wav-nnet3-latgen-faster

### ISSUE THREAD

**Issue by zloidemon** [pykaldi/pykaldi#23] opened 2018-02-07 13:40 UTC
Hello,

Can you reimplement online2-wav-nnet3-latgen-faster in your python library?

**Comment by dogancan** [comment] 2018-02-07 18:37
I am not 100% sure but I think we have all the components necessary for reimplementing online2-wav-nnet3-latgen-faster in python. All that is needed is a python script similar to [this one](https://github.com/pykaldi/pykaldi/blob/master/examples/gmm-decode-faster/gmm-decode-faster.py). That being said, I don't see the benefit of reimplementing this decoder in pykaldi apart from showing how it can be done in pykaldi. I mean why not use the online2-wav-nnet3-latgen-faster binary in kaldi instead? If you don't mind me asking, what is the use case you have in mind that is not answered by the existing kaldi binary? Maybe when you said "reimplement online2-wav-nnet3-latgen-faster", you meant something else?

**Comment by zloidemon** [comment] 2018-02-07 18:51
I want implement something like this https://github.com/dialogflow/asr-server in python but I still in compiling progress docker container. I spend a few days without results to get working env of pykaldi and  still have issues and can even test examples. If you will give me advice to see parts of your library what i need to do service like asr-server i would be happy to drill down into pykaldi.

**Comment by dogancan** [comment] 2018-02-07 19:33
I am sorry to hear you had problems with getting a working pykaldi environment. Feel free to open an issue about your troubles and we will try and help you resolve them. @vrmpx is working on a new set of installation scripts that you can take a look at #22, which we hope will make it easier to install pykaldi.

It is hard for me to say exactly what you will need for implementing an asr-server like the one you linked since I am not familiar with it. Is there something specific that you were looking for but could not find in pykaldi? I am guessing pykaldi already has most (if not all) of the components you will need for implementing an online nnet3 based asr-server (see asr module and decoder, fstext, lat, feat, online2, nnet3 packages). Unfortunately pykaldi documentation for some of these packages is not in a great state yet so for the moment you will have to rely on kaldi documentation for those packages.

**Comment by vrmpx** [comment] 2018-02-07 21:37
Hi @zloidemon 

I just updated the pre-built image at DockerHub. That would help with the issue of your dockerfile hanging. You can get it via 

```
docker pull vrmpx/pykaldi
```

I hope that helps.

**Comment by zloidemon** [comment] 2018-02-09 11:13
I can not install
```
# docker pull vrmpx/pykaldi
Using default tag: latest
latest: Pulling from vrmpx/pykaldi
660c48dd555d: Pull complete 
4c7380416e78: Pull complete 
421e436b5f80: Pull complete 
e4ce6c3651b3: Pull complete 
be588e74bd34: Pull complete 
5dfe216cb534: Pull complete 
c51fd3663f33: Pull complete 
772206ec03ea: Pull complete 
b7212c3e59da: Pull complete 
9bc24434474b: Pull complete 
fc5bb4481109: Pull complete 
455a9fff4ec5: Extracting  1.286GB/1.286GB
a7debf1031f8: Download complete 
bd15391642d7: Download complete 
b49ad5187335: Download complete 
e545e99b50bd: Download complete 
failed to register layer: ApplyLayer exit status 1 stdout:  stderr: write /root/kaldi/tools/openfst-1.6.5/src/extensions/far/far-class.o: no space left on device
```

And I have a free space
```
# df -h
Filesystem      Size  Used Avail Use% Mounted on
udev            3.0G     0  3.0G   0% /dev
tmpfs           601M  8.1M  593M   2% /run
/dev/xvda        99G   38G   57G  40% /
tmpfs           3.0G   12K  3.0G   1% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           3.0G     0  3.0G   0% /sys/fs/cgroup
cgmfs           100K     0  100K   0% /run/cgmanager/fs
tmpfs           601M     0  601M   0% /run/user/1003
```

**Comment by dogancan** [comment] 2018-02-09 19:23
I am guessing the docker images on your system have exhausted the inodes for the root volume which is where docker puts its images by default. Try running `df -i` to see if you have any free inodes left for the root volume.

If the problem is indeed the docker images exhausting inodes, you can try the following commands.
The first command removes dangling images. Check inode usage again after running this command to see if things returned to normal. The second command removes images for containers that are not currently running. Don't run this command if you don't want that to happen.

```bash
# remove dangling images
docker rmi $(docker images -q --filter "dangling=true")

# remove stopped containers
docker rm $(docker ps -a -q)
```

**Comment by dogancan** [comment] 2018-04-20 18:32
I am closing this since I am not sure if there is anything particular to do on our end. Maybe I am missing something here so feel free to reopen if you disagree.

**Closed by dogancan** 2018-04-20 18:32 UTC

**Comment by sid619sid** [comment] 2020-03-03 06:47
> I am sorry to hear you had problems with getting a working pykaldi environment. Feel free to open an issue about your troubles and we will try and help you resolve them. @vrmpx is working on a new set of installation scripts that you can take a look at #22, which we hope will make it easier to install pykaldi.
> 
> It is hard for me to say exactly what you will need for implementing an asr-server like the one you linked since I am not familiar with it. Is there something specific that you were looking for but could not find in pykaldi? I am guessing pykaldi already has most (if not all) of the components you will need for implementing an online nnet3 based asr-server (see asr module and decoder, fstext, lat, feat, online2, nnet3 packages). Unfortunately pykaldi documentation for some of these packages is not in a great state yet so for the moment you will have to rely on kaldi documentation for those packages.

hai @dogancan the page you mentioned is not accessible page is throwing 404 error could you give me some other source for pykaldi .
